---
- hosts: workers
  roles:
    - { role: dj-wasabi.telegraf }
  sudo: yes
  gather_facts: yes
  vars:
    - telegraf_agent_output:
      - type: influxdb
        config:
          - urls = ["http://10.254.1.5:8086"]
          - database = "telegraf"
          - precision = "s"
